#!/usr/bin/env lua


io.input(arg[1]) -- SRT file
textosrt = string.sub(arg[1], 1, -5)
textoass = textosrt .. ".ass"
textosrt = textosrt .. ".srt"
io.output(textoass) -- ASS file

io.write("[Script Info]\n")
io.write("; Script generated by Rafael Lima\n")
io.write(";\n")
io.write("Title: Default Aegisub file \n")
io.write("ScriptType: v4.00+ \n")
io.write("WrapStyle: 0 \n")
io.write("PlayResX: 640 \nPlayResY: 480 \n")
io.write("ScaledBorderAndShadow: yes \n")
io.write("Last Style Storage: DarkSide\n")
io.write("Export Encoding: ISO-8859-1\n \n[V4+ Styles]\n")
io.write("Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n")
io.write("Style: Default,Arial,26,&H00FFFFFF,&H00888888,&H00000000,&HAA000000,-1,0,0,0,100,100,0,0,1,2,2,2,10,10,40,1\n")
io.write("Style: Italico,Arial,26,&H00FFFFFF,&H00888888,&H00000000,&HAA000000,-1,1,0,0,100,100,0,0,1,2,2,2,10,10,40,1\n")
io.write("Style: Negr,Arial,30,&H00FFFFAA,&H00888888,&H00000000,&HAA000000,1,0,0,0,100,100,0,0,1,2,2,2,10,10,40,1\n")
io.write("\n\n\n[Events]\n")
io.write("Format: Layer, Start, End, Style, Actor, MarginL, MarginR, MarginV, Effect, Text\n")


-- SRT table memory allocation
srt_tab={
magic_number = 0,
temp_inic = " ",
temp_fim = " ",
content = " "}

-- ASS table memory allocation
ass_tab={
magic_number = 0,
temp_inic = " ",
temp_fim = " ",
content = " "}
-- Second step: read SRT file

while true do
	line = io.read()
	if (line == nil) then break end
	srt_tab.magic_number = tonumber(line)
	line = io.read()
	if (line == nil) then break end
	srt_tab.temp_inic = string.sub(line, 2, 12)
	srt_tab.temp_fim = string.sub(line, -12, -2)
	ass_tab.magic_number = srt_tab[magic_number]
	ass_tab.temp_inic = string.gsub(srt_tab.temp_inic, ",", ".")
	ass_tab.temp_fim  = string.gsub(srt_tab.temp_fim, ",", ".")
	line = io.read()
	if (line == nil) then break end
	ass_tab.content = line
	while (#line ~= 1) do
		 temporary = string.sub(ass_tab.content,1, -2)
		 
		 line = io.read()		 
		 ass_tab.content = temporary .. "\\N" .. line
		 
	end
	ass_tab.content = string.sub(ass_tab.content,1, -4)

	--Subtitle time treatment: SRT subs has 3 decimal numbers; ASS sub, however, has only 2:
	ass_tab.temp_inic = string.sub(ass_tab.temp_inic, 1, -2)
	ass_tab.temp_fim  = string.sub(ass_tab.temp_fim,  1, -2)
	--end of subtitle time treatment

	-- line by line convertion
	-- checking <i> and <b> tags
	tag = string.sub(ass_tab.content, 1, 3)
	if (tag == "<i>") then
		ass_tab.content = string.sub(ass_tab.content, 4, -5)
		io.write("Dialogue: 0," .. ass_tab.temp_inic .. "," .. ass_tab.temp_fim .. ",Italico,,0000,0000,0000,," .. ass_tab.content .. "\n")
	elseif (tag == "<b>") then
		ass_tab.content = string.sub(ass_tab.content, 4, -5)
		io.write("Dialogue: 0," .. ass_tab.temp_inic .. "," .. ass_tab.temp_fim .. ",Negr,,0000,0000,0000,," .. ass_tab.content .. "\n")
	else
		io.write("Dialogue: 0," .. ass_tab.temp_inic .. "," .. ass_tab.temp_fim .. ",Default,,0000,0000,0000,," .. ass_tab.content .. "\n")
	end
	if (line == nil) then break end
end
os.execute("rm " .. textosrt);
print("File " .. textoass .. " was written with success!")
